### ISSUE TITLE
Not working in Pinokio

### ISSUE THREAD

**Issue by ETCore7** [CharafChnioune/MFLUX-WEBUI#2]
After start it ends with "ENOENT: no such file or directory, stat 'D:\pinokio\api\MFLUX-WEBUI.git\{{input.event[0]}}'"

**Comment by CharafChnioune** [comment]
What machine are you using? It uses MLX framework from apple so it won't work on windows

**Comment by ETCore7** [comment]
Thank you for your fast response. Too bad it isn't working on Windows (yet), it looks great.

**Comment by CharafChnioune** [comment]
The project is built using Apple's MLX framework, which is only compatible with macOS, and unfortunately does not support Windows at this time.

For Windows users, I recommend trying out Forge UI on Pinokio, which works well in that environment. The main reason behind creating this project was to provide a solution for macOS, particularly for M-series devices, as Forge doesn't work natively on those systems.

**Comment by ETCore7** [comment]
Thank you for clarify
