### ISSUE TITLE
Advanced Generate with Dev + Lora Broken?

### ISSUE THREAD

**Issue by 0xunderl0rd** [CharafChnioune/MFLUX-WEBUI#3]
First off, THANK YOU FOR THIS.

Secondly, having issues when using ADVANCE GENERATE along with the DEV model and a custom LORA:

> Traceback (most recent call last): File "/Users/kp/pinokio/api/MFLUX-WEBUI.git/app/env/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events response = await route_utils.call_process_api( File "/Users/kp/pinokio/api/MFLUX-WEBUI.git/app/env/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api output = await app.get_blocks().process_api( File "/Users/kp/pinokio/api/MFLUX-WEBUI.git/app/env/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api result = await self.call_function( File "/Users/kp/pinokio/api/MFLUX-WEBUI.git/app/env/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function prediction = await anyio.to_thread.run_sync(  # type: ignore File "/Users/kp/pinokio/api/MFLUX-WEBUI.git/app/env/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync return await get_async_backend().run_sync_in_worker_thread( File "/Users/kp/pinokio/api/MFLUX-WEBUI.git/app/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2405, in run_sync_in_worker_thread return await future File "/Users/kp/pinokio/api/MFLUX-WEBUI.git/app/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 914, in run result = context.run(func, *args) File "/Users/kp/pinokio/api/MFLUX-WEBUI.git/app/env/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper response = f(*args, **kwargs) File "/Users/kp/pinokio/api/MFLUX-WEBUI.git/app/webui.py", line 186, in generate_image_gradio flux = get_or_create_flux(model, quantize, None, lora_paths, None) File "/Users/kp/pinokio/api/MFLUX-WEBUI.git/app/webui.py", line 81, in get_or_create_flux flux_cache[key] = FluxClass( File "/Users/kp/pinokio/api/MFLUX-WEBUI.git/app/env/lib/python3.10/site-packages/mflux/flux/flux.py", line 46, in __init__ weights = WeightHandler( File "/Users/kp/pinokio/api/MFLUX-WEBUI.git/app/env/lib/python3.10/site-packages/mflux/weights/weight_handler.py", line 28, in __init__ LoraUtil.apply_loras(self.transformer, lora_paths, lora_scales) File "/Users/kp/pinokio/api/MFLUX-WEBUI.git/app/env/lib/python3.10/site-packages/mflux/weights/lora_util.py", line 18, in apply_loras LoraUtil._apply_lora(transformer, lora_file, lora_scale) File "/Users/kp/pinokio/api/MFLUX-WEBUI.git/app/env/lib/python3.10/site-packages/mflux/weights/lora_util.py", line 36, in _apply_lora lora_transformer, _ = WeightHandler.load_transformer(lora_path=lora_file) File "/Users/kp/pinokio/api/MFLUX-WEBUI.git/app/env/lib/python3.10/site-packages/mflux/weights/weight_handler.py", line 64, in load_transformer weights, quantization_level = WeightHandler._get_weights("transformer", root_path, lora_path) File "/Users/kp/pinokio/api/MFLUX-WEBUI.git/app/env/lib/python3.10/site-packages/mflux/weights/weight_handler.py", line 123, in _get_weights weight = list(mx.load(lora_path).items()) ValueError: [load] Could not infer file format from extension

The MLFlux "easy" tab works with this lora just fine, only the advanced gen is giving issues. I should note that advanced gen, with DEV and no lora, works fine as well.

**Comment by CharafChnioune** [comment]
Sorry for the late reply, but it should be working now. Let me know if you encounter any errors.
