### ISSUE TITLE
Controlnet doesn't work - two bugs

### ISSUE THREAD

**Issue by maxtheman** [CharafChnioune/MFLUX-WEBUI#6]
Hi there,

The code for running controlnets has two breaking issues:

First, running with schnell or anything not containing 'dev' fails due to this line:

```
    if "dev" not in model:
        guidance = None
```

with this error: `Error generating image: unsupported operand type(s) for *: 'NoneType' and 'int'`

Given the error, I assume you probably should set Guidance to 0? I don't know the particulars of why you are removing Guidance for this case, but that worked for me.

The second issue is with this line:

```
del generated_image
```
This deletes the variable before it's returned, resulting in the program crashing.

Thanks for making this app!

**Comment by CharafChnioune** [comment]
Hi @maxtheman,

Thank you so much for pointing out those issues! I’ve updated the code based on your feedback:

1. Guidance Issue: Removed the conditional setting of guidance to None for non-dev models, so guidance now defaults to a sensible value, which should avoid the NoneType error.
2. Generated Image Deletion: I moved the deletion of generated_image to the finally block, which runs after the return, so it should no longer interfere with the return value. This should prevent any crashes related to it.

In addition to those fixes, I also added image-to-image functionality! You can now try generating images based on an initial image input, which allows for some fun experimentation with controlnet and LoRA options.

Feel free to test it out and see if you can break things! :) I’d love to hear if you run into any other issues (or come up with any new ideas).

**Comment by maxtheman** [comment]
@CharafChnioune All works now! The image-to-image is interesting, I will play with it more. Thank you for the fix.
