### ISSUE TITLE
Feature Request: Seed number on all generation tabs

### ISSUE THREAD

**Issue by dzeitman** [CharafChnioune/MFLUX-WEBUI#9]
Love the MFLUX easy tab for quick inspiration -- but it would be awesome if the page returned the seed number post generation so the user could copy that over to advanced generate for fine tuning.  

In general, it would amazing if there was a way to persist the generation information to be able to "replay" past generations.

**Comment by CharafChnioune** [comment]
This feature has been implemented in the development branch! 

Now both the Easy will show the seed information in the "Saved Image Filenames" text box below the gallery. The output format looks like this:

File: generated_1234567890_0_seed_42.png (Seed: 42)
